name: banking_web_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.0
  dotted_border: ^2.1.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/air-bnb.png
    - assets/images/apple.png
    - assets/images/arrow.png
    - assets/images/card.png
    - assets/images/credit-card.png
    - assets/images/document.png
    - assets/images/logo.png
    - assets/images/main-card.png
    - assets/images/netflix.png
    - assets/images/nvidia.png
    - assets/images/qr.png
    - assets/images/vip.png
    - assets/images/visa-bkg.jpg
    - assets/images/visa.png
    - assets/images/user.jpeg
    - assets/images/search.png
    - assets/images/rotate.png
    - assets/images/credit.png
    - assets/images/24-7.png
  
  fonts:
    - family: Space_Grotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
